## Inserting data into job_openings table

insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (6, 'Senior Sales Associate', 'This is the job description', 'Jaipur(Rajasthan)', '11/26/2022', 'open', null, 'LinkedIn');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (10, 'Teacher', 'This is the job description', 'Gurgaon(Haryana)', '8/19/2022', 'closed', '11/17/2022', 'Dribble');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (4, 'Structural Engineer', 'This is the job description', 'Mumbai(Maharashtra)', '6/9/2022', 'closed', '6/11/2022', 'Glassdoor');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (6, 'Data Coordiator', 'This is the job description', 'Gurgaon(Haryana)', '9/5/2022', 'closed', '11/14/2022', 'Glassdoor');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (8, 'Analyst Programmer', 'This is the job description', 'Mumbai(Maharashtra)', '9/2/2022', 'open', null, 'Dribble');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (4, 'Internal Auditor', 'This is the job description', 'Mumbai(Maharashtra)', '7/7/2022', 'closed', '10/7/2022', 'WellFound');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (10, 'Research Assistant II', 'This is the job description', 'Jaipur(Rajasthan)', '7/24/2022', 'open', null, 'WellFound');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (2, 'Account Representative II', 'This is the job description', 'Mumbai(Maharashtra)', '10/30/2022', 'closed', '12/30/2022', 'WellFound');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (6, 'Director of Sales', 'This is the job description', 'Hyderabad(Telangana)', '7/16/2022', 'closed', '11/16/2022', 'LinkedIn');
insert into job_postings (recruiterid, title, description, work_location, posting_date, job_state, closing_date, posted_through) values (8, 'Executive Secretary', 'This is the job description', 'Hyderabad(Telangana)', '8/10/2022', 'closed', '1/16/2023', 'WellFound');